In [3]:
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [8]:
a=np.zeros((2,2))
print(a,'\n')

b=np.ones((1,2))
print(b,'\n')

c=np.full((2,2),7)
print(c,'\n')

d=np.eye(2)
print(d,'\n')

e=np.random.random((2,2))
print(e,'\n')

[[0. 0.]
 [0. 0.]] 

[[1. 1.]] 

[[7 7]
 [7 7]] 

[[1. 0.]
 [0. 1.]] 

[[0.66968481 0.51092795]
 [0.82834578 0.90368009]] 



In [13]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,'\n')
b=a[:2,1:3]
print(b,'\n')

print(a[0,1])
b[0,0]=77
print(a[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[2 3]
 [6 7]] 

2
77


In [19]:
row_r1=a[1,:]
row_r2=a[1:2,:]

print(row_r1,row_r1.shape,'\n')
print(row_r2,row_r2.shape,'\n')

col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1, col_r1.shape,'\n')
print(col_r2, col_r2.shape,'\n')

[5 6 7 8] (4,) 

[[5 6 7 8]] (1, 4) 

[77  6 10] (3,) 

[[77]
 [ 6]
 [10]] (3, 1) 



In [22]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a,'\n')
# [1 4 5] 1차원 행렬(3,)을 얻는 두 가지 방법
print(type(a[[0, 1, 2], [0, 1, 0]]),'\n')
print(type(np.array([a[0, 0], a[1, 1], a[2, 0]])),'\n')
# [2 2] 1차원 행렬(2,)을 얻는 두 가지 방법
print(a[[0, 0], [1, 1]],'\n')
print(np.array([a[0, 1], a[0, 1]]),'\n')

[[1 2]
 [3 4]
 [5 6]] 

<class 'numpy.ndarray'> 

<class 'numpy.ndarray'> 

[2 2] 

[2 2] 



In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a,'\n')

b=np.array([0,2,0,1])

print(a[np.arange(4),b],'\n')
a[np.arange(4),b]+=10
print(a,'\n')


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[ 1  6  7 11] 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]] 



In [24]:
x=np.array([1,2])
print(x.dtype)

x=np.array([1.0,2.0])
print(x.dtype)

x=np.array([1,2],dtype=np.int64)
print(x.dtype)

int64
float64
int64


In [26]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

print(x+y)
print(np.add(x,y),'\n')

print(x-y)
print(np.subtract(x,y),'\n')

print(x*y)
print(np.multiply(x,y),'\n')

print(x/y)
print(np.divide(x,y),'\n')

print(np.sqrt(x),'\n')

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]] 

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]] 

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[1.         1.41421356]
 [1.73205081 2.        ]] 



In [30]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

v=np.array([9,10])
w=np.array([11,12])

print(v.dot(w),'\n')
print(np.dot(v,w),'\n')

print(x.dot(v),'\n')
print(np.dot(x,v),'\n')

print(x.dot(y),'\n')
print(np.dot(x,y),'\n')

v2=np.reshape(v,(1,v.shape[0]))
print(v2,'\n')

219 

219 

[29 67] 

[29 67] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 

[[ 9 10]] 



In [61]:
x=np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))


10
[4 6]
[3 7]


In [33]:
x=np.array([[1,2],[3,4]])

print(x)
print(x.T)

v=np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [40]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
print(x.shape[0])

print(x,'\n')
print(v,'\n')
y = np.empty_like(x) 
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

4
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[1 0 1] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [47]:
vv = np.tile(v, (4, 1))
print(v,'\n')
print(vv,'\n')
y = x + vv
print(y,'\n')

[1 0 1] 

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] 



In [53]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
c=x.T
print(x,'\n')
print(c,'\n')
v = np.array([1,0,1]).reshape((3,1))
print(v,'\n')
y = c + v0
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] 

[[1]
 [0]
 [1]] 

[[ 2  5  8 11]
 [ 2  5  8 11]
 [ 4  7 10 13]]


In [62]:
x=np.array([[1,1],[2,1]])
y=np.array([[15],[25]])
print(x,'\n',y,'\n')
x2=numpy.linalg.inv(x)
print(np.dot(x2,y))

[[1 1]
 [2 1]] 
 [[15]
 [25]] 

[[10.]
 [ 5.]]


In [67]:
import pickle
fw=open('ffe.p','wb')
pickle.dump([{'df':'ff', 'dfdf0':'dfdf'},[1,2,3,4]],fw)
fw.close()

In [69]:
fr=open('ffe.p','rb')
pickle.load(fr)
print()
fr.close()

EOFError: Ran out of input