In [3]:
import numpy as np
import scipy.stats as sp
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest
from scipy import stats

In [2]:
df=pd.DataFrame({'sample':[74.5,81.2,73.8,82,76.3,75.7,80.2,72.6,77.9,82.8]})

In [4]:
tt=stats.ttest_1samp(df,76.7)
t,p=tt.statistic.round(3),tt.pvalue.round(3)
print('t검정통계량' , t)
print('p_value', p)

t검정통계량 [0.864]
p_value [0.41]


In [5]:
df=pd.DataFrame({'sample':[85,79,79.1,79.9,81.6,78.6,85.4,83.4,78.1,79.2]})
tt=stats.ttest_1samp(df,76.7)
t,p=tt.statistic.round(3),tt.pvalue.round(3)
print('t검정통계량' , t)
print('p_value', p)

t검정통계량 [4.879]
p_value [0.001]


In [6]:
df1=pd.DataFrame({'sample1':[6,5,5,4,6,7,6,4,5,6,4,5,5,6,4,8,6,5,6,7]})
df2=pd.DataFrame({'sample2':[7,5,7,8,7,8,8,5,7,6,5,5,6,6,5,7,9,7,7,8]})
tt=stats.ttest_ind(df1,df2)
t,p=tt.statistic.round(3),tt.pvalue.round(3)
print('t검정통계량' , t)
print('p_value', p)

t검정통계량 [-3.122]
p_value [0.003]


In [7]:
df1=pd.DataFrame({'sample1':[1.883,1.715,1.799,1.768,1.711,1.832,1.427,1.344]})
df2=pd.DataFrame({'sample2':[1.435,1.572,1.486,1.511,1.457,1.548,1.404,1.883]})
tt=stats.ttest_ind(df1,df2)
t,p=tt.statistic.round(3),tt.pvalue.round(3)
print('t검정통계량' , t)
print('p_value', p)

t검정통계량 [1.7]
p_value [0.111]


In [8]:
df1=pd.DataFrame({'before':[720,589,780,648,720,589,780,648,780,648]})
df2=pd.DataFrame({'after':[810,670,790,712,810,670,790,712,790,712]})
tt=stats.ttest_rel(df1,df2)
t,p=tt.statistic.round(3),tt.pvalue.round(3)
print('t검정통계량' , t)
print('p_value', p)

t검정통계량 [-5.324]
p_value [0.]


In [9]:
df1=pd.DataFrame({'before':[720,589,780,648,720,589,780,648,780,648]})
df2=pd.DataFrame({'after':[710,580,787,712,750,600,782,670,790,680]})
tt=stats.ttest_rel(df1,df2)
t,p=tt.statistic.round(3),tt.pvalue.round(3)
print('t검정통계량' , t)
print('p_value', p)

t검정통계량 [-2.266]
p_value [0.05]


In [11]:
df1=pd.DataFrame({'a':[892,623,721,678,723,790,720,670,690,771]})
df2=pd.DataFrame({'b':[721,821,910,678,723,790,711,790,745,891]})
df3=pd.DataFrame({'c':[621,915,888,721,894,834,841,912,845,889]})
ft=stats.f_oneway(df1,df2,df3)
f,p=ft.statistic.round(3),ft.pvalue.round(3)
print('t검정통계량' , f)
print('p_value', p)

t검정통계량 [4.263]
p_value [0.025]


In [13]:
from statsmodels.stats.proportion import proportions_ztest
count=15
nobs=100
value=.1
stat,pval=proportions_ztest(count,nobs,value)
print('p',stat)
print('p-value',pval)

p 1.4002800840280094
p-value 0.16142946236708322


In [14]:
from statsmodels.stats.proportion import proportions_ztest
count=10
nobs=100
value=.2
stat,pval=proportions_ztest(count,nobs,value)
print('p',stat)
print('p-value',pval)

p -3.333333333333333
p-value 0.0008581206663936744


In [17]:
count=np.array([4,1])
nobs=np.array([1000,1200])
stat,pval=proportions_ztest(count,nobs)
print('p', stat)
print('p_value', pval)

p 1.553109404737079
p_value 0.12039699966295712


In [18]:
count=np.array([14,5])
nobs=np.array([1200,1200])
stat,pval=proportions_ztest(count,nobs)
print('p', stat)
print('p_value', pval)

p 2.0729633895345208
p_value 0.03817568685216671


In [22]:
df=pd.DataFrame({'hsg':[270,260,236,234],'ss':[228,285,225,262],'spa':[277,284,231,208]})
chi,pval,dof,expected=stats.chi2_contingency(df.T)
print('chisq',chi)
print('df',dof)
print('p',pval)
print('expected value \n',expected)

chisq 13.36627391246374
df 6
p 0.03757449387917438
expected value 
 [[258.33333333 276.33333333 230.66666667 234.66666667]
 [258.33333333 276.33333333 230.66666667 234.66666667]
 [258.33333333 276.33333333 230.66666667 234.66666667]]


In [24]:
df=pd.DataFrame({'A/S':[18,8,4,4,3,3],'PRICE':[1,2,1,1,1,25],'SPEC':[8,14,3,2,3,8],'FLEXIBILITY':[7,5,4,3,1,10]\
                ,'DSESIGN':[10,5,9,2,1,2],'SAFETY':[9,9,5,7,1,1],'FUNCTION':[10,4,4,3,1,7]})
chi,pval,dof,expected=stats.chi2_contingency(df.T)
print('chisq',chi)
print('df',dof)
print('p',pval)
print('expected value \n',expected)

chisq 98.27432228716901
df 30
p 3.4707443967367854e-09
expected value 
 [[11.00436681  8.20960699  5.24017467  3.84279476  1.92139738  9.78165939]
 [ 8.52838428  6.36244541  4.06113537  2.97816594  1.48908297  7.58078603]
 [10.45414847  7.79912664  4.97816594  3.65065502  1.82532751  9.29257642]
 [ 8.25327511  6.15720524  3.930131    2.88209607  1.44104803  7.33624454]
 [ 7.97816594  5.95196507  3.79912664  2.7860262   1.3930131   7.09170306]
 [ 8.80349345  6.56768559  4.19213974  3.07423581  1.5371179   7.82532751]
 [ 7.97816594  5.95196507  3.79912664  2.7860262   1.3930131   7.09170306]]


In [30]:
df1=[1,2,3,4,4,5,6,6,7,8]
df2=[23,29,49,64,74,87,96,97,109,119]
corr,pval=sp.pearsonr(df1,df2)
print('corr', corr)
print('p {0:0.03f}'.format(pval))

corr 0.9892262536728125
p 0.000


In [31]:
df1=[37.6,38.6,37.2,36.4,38.6,39,37.2,36.1,35.9,37.1,36.9,37.5,36.3,38.1,39,36.9,36.8,37.6,33,33.5]
df2=[14,15,14,16,17,14,17,16,15,16,14,16,18,13,15,17,14,16,20,21]
corr,pval=sp.pearsonr(df1,df2)
print('corr', corr)
print('p {0:0.03f}'.format(pval))

corr -0.7231073149351571
p 0.000


In [32]:
minutes=[1,2,3,4,4,5,6,6,7,8]
units=[23,29,49,64,74,87,96,97,109,119]
minutes=sm.add_constant(minutes)
model=sm.OLS(units,minutes)
result=model.fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.979
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     365.3
Date:                Fri, 26 Apr 2019   Prob (F-statistic):           5.82e-08
Time:                        13:32:59   Log-Likelihood:                -29.401
No. Observations:                  10   AIC:                             62.80
Df Residuals:                       8   BIC:                             63.41
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.1712      3.886      1.845      0.1

/home/pirl/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


In [35]:
stren=[37.6,38.6,37.2,36.4,38.6,39,37.2,36.1,35.9,37.1,36.9,37.5,36.3,38.1,39,36.9,36.8,37.6,33,33.5]
time=[0.798922,0.84902,0.816163,0.758266,0.815894,0.807477,0.809068,0.7664,0.742243,0.751118,0.740629,0.751495,0.738863,0.827428,0.818172,0.1740939,0.757128,0.804695,0.695121,0.735377]

stren=sm.add_constant(stren)
model=sm.OLS(time,stren)
result=model.fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.058
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     1.115
Date:                Fri, 26 Apr 2019   Prob (F-statistic):              0.305
Time:                        13:37:41   Log-Likelihood:                 11.940
No. Observations:                  20   AIC:                            -19.88
Df Residuals:                      18   BIC:                            -17.89
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0553      0.761     -0.073      0.9

In [36]:
from numpy.random import randn

In [40]:
np.random.seed(1234)
df=pd.DataFrame(randn(10,2),columns=['A','B'])
df

A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
2 -0.720589  0.887163
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118
8  0.405453  0.289092
9  1.321158 -1.546906

In [41]:
df['A']

0    0.471435
1    1.432707
2   -0.720589
3    0.859588
4    0.015696
5    1.150036
6    0.953324
7   -0.334077
8    0.405453
9    1.321158
Name: A, dtype: float64

In [42]:
df[['A']]

A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077
8  0.405453
9  1.321158

In [43]:
df[0:5]

A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
2 -0.720589  0.887163
3  0.859588 -0.636524
4  0.015696 -2.242685

In [44]:
df.loc[0:7,['A']]

A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077

In [45]:
df.loc[:,['A']]

A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077
8  0.405453
9  1.321158

In [46]:
df.loc[3:8]

A         B
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118
8  0.405453  0.289092

In [47]:
df.loc[3:3]

A         B
3  0.859588 -0.636524

In [48]:
df.iloc[0:7,[0]]

A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324

In [49]:
df.iloc[:,[0]]

A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077
8  0.405453
9  1.321158

In [50]:
df.iloc[3:8]

A         B
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118

In [51]:
df.iloc[3:4]

A         B
3  0.859588 -0.636524

In [52]:
df.query('A>0.5')

A         B
1  1.432707 -0.312652
3  0.859588 -0.636524
5  1.150036  0.991946
6  0.953324 -2.021255
9  1.321158 -1.546906

In [53]:
df.query('A>B')

A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
8  0.405453  0.289092
9  1.321158 -1.546906

In [54]:
df[df.A>df.B]

A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
8  0.405453  0.289092
9  1.321158 -1.546906

In [55]:
np.random.seed(1234)
df=pd.DataFrame(randn(10,4),columns=['A','B','C','D'])
df

A         B         C         D
0  0.471435 -1.190976  1.432707 -0.312652
1 -0.720589  0.887163  0.859588 -0.636524
2  0.015696 -2.242685  1.150036  0.991946
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092
9  0.124713 -0.322795  0.841675  2.390961

In [56]:
df.loc[3:8]

A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

In [57]:
df.iloc[3:8]

A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438

In [58]:
df.query('A>B')

A         B         C         D
0  0.471435 -1.190976  1.432707 -0.312652
2  0.015696 -2.242685  1.150036  0.991946
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
8  1.047579  1.045938  0.863717 -0.122092
9  0.124713 -0.322795  0.841675  2.390961

In [105]:
df1=pd.DataFrame({'a':['a0','a1','a2','a3'],'b':['b0','b1','b2','b3'],'c':['c0','c1','c2','c3'],'d':['d0','d1','d2','d3']}\
                ,index=[0,1,2,3])
df2=pd.DataFrame({'a':['a4','a5','a6','a7'],'b':['b4','b5','b6','b7'],'c':['c4','c5','c6','c7'],'d':['d4','d5','d6','d7']}\
                ,index=[4,5,6,7])
df3=pd.DataFrame({'a':['a8','a9','a10','a11'],'b':['b8','b9','b10','b11'],'c':['c8','c9','c10','c11'],\
                  'd':['d8','d9','d10','d11']},index=[8,9,10,11])


In [106]:
result=pd.concat([df1,df2,df3])
result

a    b    c    d
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11

In [107]:
result=pd.concat([df1,df2,df3],axis=1)
result

a    b    c    d    a    b    c    d    a    b    c    d
0    a0   b0   c0   d0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    a1   b1   c1   d1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    a2   b2   c2   d2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    a3   b3   c3   d3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   a4   b4   c4   d4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   a5   b5   c5   d5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   a6   b6   c6   d6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   a7   b7   c7   d7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   a8   b8   c8   d8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   a9   b9   c9   d9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  a10  b10  c10  d10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  a11  b11  c11  d11

In [108]:
reuslt=pd.concat([df1,df2,df3],axis=1,ignore_index=True)
result.columns=['col_'+str(i) for i in range(12)]
result

col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10 col_11
0     a0    b0    c0    d0   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
1     a1    b1    c1    d1   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
2     a2    b2    c2    d2   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
3     a3    b3    c3    d3   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN
4    NaN   NaN   NaN   NaN    a4    b4    c4    d4   NaN   NaN    NaN    NaN
5    NaN   NaN   NaN   NaN    a5    b5    c5    d5   NaN   NaN    NaN    NaN
6    NaN   NaN   NaN   NaN    a6    b6    c6    d6   NaN   NaN    NaN    NaN
7    NaN   NaN   NaN   NaN    a7    b7    c7    d7   NaN   NaN    NaN    NaN
8    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    a8    b8     c8     d8
9    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    a9    b9     c9     d9
10   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   a10   b10    c10    d10
11   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   a11   b11    c11    d11

In [109]:
df1=pd.DataFrame({'a':['a0','a1','a2','a3'],'b':['b0','b1','b2','b3'],'c':['c0','c1','c2','c3'],'d':['d0','d1','d2','d3']})
df2=pd.DataFrame({'a':['a4','a5','a6','a7'],'b':['b4','b5','b6','b7'],'c':['c4','c5','c6','c7'],'d':['d4','d5','d6','d7']})
df3=pd.DataFrame({'a':['a8','a9','a10','a11'],'b':['b8','b9','b10','b11'],'c':['c8','c9','c10','c11'],\
                  'd':['d8','d9','d10','d11']})


In [110]:
result=pd.concat([df1,df2,df3],axis=1)
result

a   b   c   d   a   b   c   d    a    b    c    d
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [111]:
left=pd.DataFrame({'key1':['k0','k1','k2','k3'],'key2':['k0','k1','k0','k1'],'a':['a0','a1','a2','a3'],\
                  'b':['b0','b1','b2','b3']})
right=pd.DataFrame({'key1':['k0','k1','k2','k3'],'key2':['k0','k0','k0','k0'],'c':['c0','c1','c2','c3'],\
                  'd':['d0','d1','d2','d3']})


In [112]:
result=pd.merge(left,right,on=['key1','key2'])
result

key1 key2   a   b   c   d
0   k0   k0  a0  b0  c0  d0
1   k2   k0  a2  b2  c2  d2

In [113]:
result=pd.merge(left,right,on=['key1','key2'],how='left')
result

key1 key2   a   b    c    d
0   k0   k0  a0  b0   c0   d0
1   k1   k1  a1  b1  NaN  NaN
2   k2   k0  a2  b2   c2   d2
3   k3   k1  a3  b3  NaN  NaN

In [114]:
result=pd.merge(left,right,on=['key1','key2'],how='right')
result

key1 key2    a    b   c   d
0   k0   k0   a0   b0  c0  d0
1   k2   k0   a2   b2  c2  d2
2   k1   k0  NaN  NaN  c1  d1
3   k3   k0  NaN  NaN  c3  d3

In [115]:
result=pd.merge(left,right,on=['key1','key2'],how='left',indicator=True)
result

key1 key2   a   b    c    d     _merge
0   k0   k0  a0  b0   c0   d0       both
1   k1   k1  a1  b1  NaN  NaN  left_only
2   k2   k0  a2  b2   c2   d2       both
3   k3   k1  a3  b3  NaN  NaN  left_only

In [120]:
left=pd.DataFrame({'key1':[1,2,3,4],'a':['a0','a1','a2','a3'],'b':['b0','b1','b2','b3']})
right=pd.DataFrame({'c':['c0','c1','c5'],'d':['d0','d1','d5']},index=[1,2,5])


In [121]:
result=left.join(right)
result

key1   a   b    c    d
0     1  a0  b0  NaN  NaN
1     2  a1  b1   c0   d0
2     3  a2  b2   c1   d1
3     4  a3  b3  NaN  NaN

In [122]:
result=left.join(right,how='right')
result

key1    a    b   c   d
1   2.0   a1   b1  c0  d0
2   3.0   a2   b2  c1  d1
5   NaN  NaN  NaN  c5  d5

In [123]:
result=left.join(right,how='inner')
result

key1   a   b   c   d
1     2  a1  b1  c0  d0
2     3  a2  b2  c1  d1

In [124]:
result=left.join(right,how='outer')
result

key1    a    b    c    d
0   1.0   a0   b0  NaN  NaN
1   2.0   a1   b1   c0   d0
2   3.0   a2   b2   c1   d1
3   4.0   a3   b3  NaN  NaN
5   NaN  NaN  NaN   c5   d5

In [125]:
result=left.join(right,on='key1')
result

key1   a   b    c    d
0     1  a0  b0   c0   d0
1     2  a1  b1   c1   d1
2     3  a2  b2  NaN  NaN
3     4  a3  b3  NaN  NaN

In [129]:
result=pd.merge(left,right,left_on='key1',right_index=True,how='left')
result

key1   a   b    c    d
0     1  a0  b0   c0   d0
1     2  a1  b1   c1   d1
2     3  a2  b2  NaN  NaN
3     4  a3  b3  NaN  NaN

In [134]:
df=pd.DataFrame({'foo':['one','one','one','two','two','two'],'bar':['a','b','c','a','b','c'],'baz':[1,2,3,4,5,6],\
                 'zoo':['x','y','z','q','w','t']})
df.pivot(index='foo',columns='bar',values='baz')

bar  a  b  c
foo         
one  1  2  3
two  4  5  6

In [135]:
df.melt(id_vars=['foo','bar'])

foo bar variable value
0   one   a      baz     1
1   one   b      baz     2
2   one   c      baz     3
3   two   a      baz     4
4   two   b      baz     5
5   two   c      baz     6
6   one   a      zoo     x
7   one   b      zoo     y
8   one   c      zoo     z
9   two   a      zoo     q
10  two   b      zoo     w
11  two   c      zoo     t

In [136]:
df.melt(id_vars=['foo','bar'],value_vars=['zoo'])

foo bar variable value
0  one   a      zoo     x
1  one   b      zoo     y
2  one   c      zoo     z
3  two   a      zoo     q
4  two   b      zoo     w
5  two   c      zoo     t

In [229]:
data=pd.read_csv('FITNESS.csv')

In [141]:
data

NAME GENDER  AGE  AGEGROUP  WEIGHT     OXY  RUNTIME  RUNPULSE  \
0      Donna      F   42        40   68.15  59.571     8.17       166   
1     Gracie          38        30   81.87  60.055     8.63       170   
2     Luanne      F   43        40   85.84  54.297     8.65       156   
3       Mimi      F   50        50   70.87  54.625     8.92       146   
4      Chris      M   49        40   70.00  49.156     8.95       180   
5      Allen      M   38        30   89.02  49.874     9.22       178   
6      Nancy      F   49        40   76.32  48.673     9.40       186   
7      Patty      F   52        50   76.32  45.441     9.63       164   
8    Suzanne      F   57        50   59.08  50.545     9.93       148   
9     Teresa      F   51        50   77.91  46.672    10.00       162   
10       Bob      M   39        30   75.07  45.313    10.07       185   
11  Harriett      F   49        40   73.37  50.388    10.08       168   
12      Jane      F   44        40   73.03  50.541    10.13       168   
13    Harold      M   48        40   91.63  46.774    10.25       162   
14     Sammy      M   54        50   83.12  51.855    10.33       166   
15     Buffy      F   52        50   73.71  45.790    10.47       186   
16     Trent      M   38        30   82.78  47.467    10.50       170   
17    Jackie      F   47        40   79.15  47.273    10.60       162   
18     Ralph      M   43        40   66.00  49.091    10.85       162   
19      Jack      M   51        50   69.63  40.836    10.95       168   
20     Annie      F   51        50   67.25  45.118    11.08       172   
21      Kate      F   45        40   66.45  44.754    11.12       176   
22      Carl      M   54        50   79.38  46.080    11.17       156   
23       Don      M   44        30   89.47  44.609    11.37       178   
24     Effie      F   48        40   61.24  47.920    11.50       170   
25    George      M   37        30   77.45  44.811    11.63       176   
26      Iris      F   39        30   75.98  45.681    11.95       176   
27      Mark      M   57        50   73.37  39.407    12.63       174   
28     Steve      M   54        50   91.63  39.203    12.88       168   
29    Vaughn      M   44        40   81.42  39.442    13.08       174   
30   William      M   45        40   87.66  37.388    14.03       186   

    RSTPULSE  MAXPULSE  
0         40       172  
1         48       186  
2         45       168  
3         48       155  
4         44       185  
5         55       180  
6         56       188  
7         48       166  
8         49       155  
9         48       168  
10        62       185  
11        67       168  
12        45       168  
13        48       164  
14        50       170  
15        59       188  
16        53       172  
17        47       164  
18        64       170  
19        57       172  
20        48       172  
21        51       176  
22        62       165  
23        62       182  
24        52       176  
25        58       176  
26        70       180  
27        58       176  
28       144       172  
29        63       176  
30        56       192

In [142]:
df=pd.DataFrame({'foo':['one','one','one'],'bar':['a','b','c'],'baz':[1,2,3],'zoo':['x','y','z']})
df

foo bar  baz zoo
0  one   a    1   x
1  one   b    2   y
2  one   c    3   z

In [143]:
df_stack=df.stack()
df_stack

0  foo    one
   bar      a
   baz      1
   zoo      x
1  foo    one
   bar      b
   baz      2
   zoo      y
2  foo    one
   bar      c
   baz      3
   zoo      z
dtype: object

In [144]:
df_unstack=df_stack.unstack()
df_unstack

foo bar baz zoo
0  one   a   1   x
1  one   b   2   y
2  one   c   3   z

In [148]:
data1=pd.read_csv('FITNESS_1.csv')
data2=pd.read_csv('FITNESS_2.csv')
data2


NAME GENDER  AGE     OXY  RUNTIME  RUNPULSE  RSTPULSE  MAXPULSE
0      Donna      f   42  59.571     8.17       166        40       172
1     Gracie      m   38  60.055     8.63       170        48       186
2     Luanne      f   43  54.297     8.65       156        45       168
3       Mimi      f   50  54.625     8.92       146        48       155
4      Chris      f   49  49.156     8.95       180        44       185
5      Allen      m   38  49.874     9.22       178        55       180
6      Nancy      f   49  48.673     9.40       186        56       188
7      Patty      f   52  45.441     9.63       164        48       166
8    Suzanne      f   57  50.545     9.93       148        49       155
9     Teresa      f   51  46.672    10.00       162        48       168
10       Bob      m   39  45.313    10.07       185        62       185
11  Harriett      m   49  50.388    10.08       168        67       168
12      Jane      m   44  50.541    10.13       168        45       168
13    Harold      m   48  46.774    10.25       162        48       164
14     Sammy      m   54  51.855    10.33       166        50       170
15     Buffy      m   52  45.790    10.47       186        59       188
16     Trent      m   38  47.467    10.50       170        53       172
17    Jackie      m   47  47.273    10.60       162        47       164
18     Ralph      m   43  49.091    10.85       162        64       170
19      Jack      m   51  40.836    10.95       168        57       172
20     Annie      f   51  45.118    11.08       172        48       172
21      Kate      f   45  44.754    11.12       176        51       176
22      Carl      m   54  46.080    11.17       156        62       165
23       Don      m   44  44.609    11.37       178        62       182
24     Effie      f   48  47.920    11.50       170        52       176
25    George      m   37  44.811    11.63       176        58       176
26      Iris      f   39  45.681    11.95       176        70       180
27      Mark      m   57  39.407    12.63       174        58       176
28     Steve      m   54  39.203    12.88       168        44       172
29    Vaughn      m   44  39.442    13.08       174        63       176
30   William      m   45  37.388    14.03       186        56       192

In [151]:
data3=pd.merge(data1,data2,on='NAME')
data3

NAME GENDER_x  AGE_x  AGEGROUP  WEIGHT GENDER_y  AGE_y     OXY  \
0      Donna        f     42        40   68.15        f     42  59.571   
1     Gracie        f     38        30   81.87        m     38  60.055   
2     Luanne        m     43        40   85.84        f     43  54.297   
3       Mimi        m     50        50   70.87        f     50  54.625   
4      Chris        m     49        40   81.42        f     49  49.156   
5      Allen        m     38        30   89.02        m     38  49.874   
6      Nancy        f     49        40   76.32        f     49  48.673   
7      Patty        m     52        50   76.32        f     52  45.441   
8    Suzanne        f     57        50   59.08        f     57  50.545   
9     Teresa        f     51        50   77.91        f     51  46.672   
10       Bob        m     39        30   75.07        m     39  45.313   
11  Harriett        m     49        40   73.37        m     49  50.388   
12      Jane        m     44        40   73.03        m     44  50.541   
13    Harold        f     48        40   91.63        m     48  46.774   
14     Sammy        f     54        50   83.12        m     54  51.855   
15     Buffy        m     52        50   73.71        m     52  45.790   
16     Trent        f     38        30   82.78        m     38  47.467   
17    Jackie        m     47        40   79.15        m     47  47.273   
18     Ralph        m     43        40   81.19        m     43  49.091   
19      Jack        m     51        50   69.63        m     51  40.836   
20     Annie        f     51        50   67.25        f     51  45.118   
21      Kate        f     45        40   66.45        f     45  44.754   
22      Carl        m     54        50   79.38        m     54  46.080   
23       Don        m     44        40   89.47        m     44  44.609   
24     Effie        f     48        40   61.24        f     48  47.920   
25    George        m     37        30   77.45        m     37  44.811   
26      Iris        f     39        30   75.98        f     39  45.681   
27      Mark        m     57        50   73.37        m     57  39.407   
28     Steve        m     54        50   91.63        m     54  39.203   
29    Vaughn        f     44        40   81.42        m     44  39.442   
30   William        m     45        40   87.66        m     45  37.388   

    RUNTIME  RUNPULSE  RSTPULSE  MAXPULSE  
0      8.17       166        40       172  
1      8.63       170        48       186  
2      8.65       156        45       168  
3      8.92       146        48       155  
4      8.95       180        44       185  
5      9.22       178        55       180  
6      9.40       186        56       188  
7      9.63       164        48       166  
8      9.93       148        49       155  
9     10.00       162        48       168  
10    10.07       185        62       185  
11    10.08       168        67       168  
12    10.13       168        45       168  
13    10.25       162        48       164  
14    10.33       166        50       170  
15    10.47       186        59       188  
16    10.50       170        53       172  
17    10.60       162        47       164  
18    10.85       162        64       170  
19    10.95       168        57       172  
20    11.08       172        48       172  
21    11.12       176        51       176  
22    11.17       156        62       165  
23    11.37       178        62       182  
24    11.50       170        52       176  
25    11.63       176        58       176  
26    11.95       176        70       180  
27    12.63       174        58       176  
28    12.88       168        44       172  
29    13.08       174        63       176  
30    14.03       186        56       192

In [230]:
data

NAME GENDER  AGE  AGEGROUP  WEIGHT     OXY  RUNTIME  RUNPULSE  \
0      Donna      F   42        40   68.15  59.571     8.17       166   
1     Gracie      F   38        30   81.87  60.055     8.63       170   
2     Luanne      F   43        40   85.84  54.297     8.65       156   
3       Mimi      F   50        50   70.87  54.625     8.92       146   
4      Chris      M   49        40   70.00  49.156     8.95       180   
5      Allen      M   38        30   89.02  49.874     9.22       178   
6      Nancy      F   49        40   76.32  48.673     9.40       186   
7      Patty      F   52        50   76.32  45.441     9.63       164   
8    Suzanne      F   57        50   59.08  50.545     9.93       148   
9     Teresa      F   51        50   77.91  46.672    10.00       162   
10       Bob      M   39        30   75.07  45.313    10.07       185   
11  Harriett      F   49        40   73.37  50.388    10.08       168   
12      Jane      F   44        40   73.03  50.541    10.13       168   
13    Harold      M   48        40   91.63  46.774    10.25       162   
14     Sammy      M   54        50   83.12  51.855    10.33       166   
15     Buffy      F   52        50   73.71  45.790    10.47       186   
16     Trent      M   38        30   82.78  47.467    10.50       170   
17    Jackie      F   47        40   79.15  47.273    10.60       162   
18     Ralph      M   43        40   66.00  49.091    10.85       162   
19      Jack      M   51        50   69.63  40.836    10.95       168   
20     Annie      F   51        50   67.25  45.118    11.08       172   
21      Kate      F   45        40   66.45  44.754    11.12       176   
22      Carl      M   54        50   79.38  46.080    11.17       156   
23       Don      M   44        30   89.47  44.609    11.37       178   
24     Effie      F   48        40   61.24  47.920    11.50       170   
25    George      M   37        30   77.45  44.811    11.63       176   
26      Iris      F   39        30   75.98  45.681    11.95       176   
27      Mark      M   57        50   73.37  39.407    12.63       174   
28     Steve      M   54        50   91.63  39.203    12.88       168   
29    Vaughn      M   44        40   81.42  39.442    13.08       174   
30   William      M   45        40   87.66  37.388    14.03       186   

    RSTPULSE  MAXPULSE  
0         40       172  
1         48       186  
2         45       168  
3         48       155  
4         44       185  
5         55       180  
6         56       188  
7         48       166  
8         49       155  
9         48       168  
10        62       185  
11        67       168  
12        45       168  
13        48       164  
14        50       170  
15        59       188  
16        53       172  
17        47       164  
18        64       170  
19        57       172  
20        48       172  
21        51       176  
22        62       165  
23        62       182  
24        52       176  
25        58       176  
26        70       180  
27        58       176  
28       144       172  
29        63       176  
30        56       192

In [9]:
data=pd.read_csv('FITNESS.csv')
df = data.loc[:,['GENDER','AGEGROUP','WEIGHT']]
df1=pd.pivot_table(df,values='WEIGHT',index=['GENDER'],columns=['AGEGROUP'],aggfunc=np.mean)
df1

AGEGROUP     30        40         50
GENDER                              
F         75.98  72.94375  70.856667
M         82.61  79.34200  79.426000